### ISSUE TITLE
make_unique requires std=c++14

### ISSUE THREAD

**Issue by frostworx** [kpeeters/shotweb#5]
Thank you for this promising project _(might replace my nfs shared shotwell in the internal network :))_
In order to compile it ootb I had to change
`-std=c++11`
to
`-std=c++14`
in `CMakeLists.txt`
to fix
`error::make_unique is not a member of ‘std’` 
_(using gcc-10.2.0-4 on Arch Linux)_

make_unique only occurs once in https://github.com/kpeeters/shotweb/blob/master/src/Database.cc#L17

A basic test worked very fine! Please keep up the good work!

**Comment by kpeeters** [comment]
This should be fixed with 91a77ce6f3, thanks for reporting.
